group_imports = "StdExternalCrate"
max_width = 80
condense_wildcard_suffixes = true
wrap_comments = true
edition = "2021"
format_code_in_doc_comments = true
format_strings = true
normalize_comments = true
reorder_impl_items = true
