[package]
name = "common"
edition.workspace = true
version.workspace = true
authors.workspace = true

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
include_dir = { workspace = true }
cooklang = { workspace = true }
